### ISSUE TITLE
bytestreamToUMP incorrect conversion of MIDI1 pitch-bend to MIDI2

### ISSUE THREAD

**Issue by paulhuggett** [midi2-dev/AM_MIDI2.0Lib#18]
I think that the conversion of a MIDI1 pitch-bend event to MIDI2 has the bytes swapped round. The [MIDI1 messages table](https://midi.org/expanded-midi-1-0-messages-list) lists bytes 2 and 3 as LSB and MSB respectively whereas the code expects the opposite order.

This was exposed by a [unit test](https://github.com/paulhuggett/AM_MIDI2.0Lib/blob/main/unittests/test_bytestreamToUMP.cpp) (look for Midi2PitchBend) I added to increase test coverage.

The test output was:
~~~
 Input: 0xE3, 0x0, 0x40
 Actual: 0x40E30000, 0x1000000
 Expected: 0x40E30000, 0x80000000
~~~
I think that the problem is in `bytestreamToUMP::bsToUMP()`:
~~~cpp
umpMess[writeIndex] = M2Utils::scaleUp((b1<<7) + b2,14,32);
~~~
whereas I think it should be:
~~~cpp
umpMess[writeIndex] = M2Utils::scaleUp((b2<<7) + b1,14,32);
~~~
(i.e. with b1 and b2 reversed.) 

As always, just let me know if you'd like me to create a PR for this change.

**Comment by starfishmod** [comment]
This is now fixed! Thank-you!
