### ISSUE TITLE
bytestreamToUMP handling of real-time events

### ISSUE THREAD

**Issue by paulhuggett** [midi2-dev/AM_MIDI2.0Lib#19]
The MIDI1 specification says that “real Time messages can be sent at any time and may be inserted anywhere in a MIDI data stream, including between Status and Data bytes of any other MIDI messages.”

I created a test that does just that. It inserts a START message (0xFA) in the middle of the three bytes of a NOTE-ON sequence (0x91, 0x3C, 0x7F). This resulted in the NOTE-ON being lost.

~~~
  Input: 0x91, 0xFA, 0x3C, 0x7F
  Actual: 0x10FA0000
  Expected: 0x10FA0000, 0x20913C7F
~~~

I think that this problem is caused because the real-time event handling code is updating the `d0` member variable used to hold the running status value. The fix I propose is straightforward. Change `bytestreamToUMP::bytestreamParse()` from:
~~~cpp
void bytestreamParse(uint8_t midi1Byte){
    if (midi1Byte == TUNEREQUEST || midi1Byte >=  TIMINGCLOCK) {
        d0 = midi1Byte;
        bsToUMP(midi1Byte,0,0);
        return;
    }
…
~~~
to:
~~~cpp
void bytestreamParse(uint8_t midi1Byte){
    if (midi1Byte == TUNEREQUEST || midi1Byte >=  TIMINGCLOCK) {
        if (midi1Byte == TUNEREQUEST) {
            d0 = midi1Byte;
        }
        return bsToUMP(midi1Byte,0,0);
    }
~~~

Note that issue #17 that I posted earlier today also suggests a small modification to this snippet of code.

As ever, let me know if you'd prefer to see this proposal as a PR.

**Comment by starfishmod** [comment]
Fixed - and tests added. - Thanks for pointing this out
