### ISSUE TITLE
Feature request: Method to clear parsed and generated data

### ISSUE THREAD

**Issue by Psychlist1972** [midi2-dev/AM_MIDI2.0Lib#21]
Request:

the `bytestreamParse` function takes in a number of bytes. The `UMPStreamParse` function does the same for UMPs.

When processing a stream of data and sending messages, if something fails, there's no clean way to clear that data and start over. Instead, we have to tear down and recreate the objects. We have some long-lived translation objects in Windows MIDI Services. 

The request is for a method to clear all parsed data including any generated or read UMPs and bytes

**Comment by starfishmod** [comment]
@Psychlist1972 this should be able to do what you are after now
