### ISSUE TITLE
umpToMIDI1Protocol::increaseWrite(void) missing

### ISSUE THREAD

**Issue by Psychlist1972** [midi2-dev/AM_MIDI2.0Lib#8]
I'm getting a linker error after grabbing the latest vcpkg. 

`umpToMIDI1Protocol::increaseWrite(void)` is missing from the lib

I looked around in this repo and I couldn't find a body for this method so I assume there's a missing file

```cpp
LNK2019	unresolved external symbol 
"private: void __cdecl umpToMIDI1Protocol::increaseWrite(void)" 
(?increaseWrite@umpToMIDI1Protocol@@AEAAXXZ) 

referenced in function 
"public: void __cdecl umpToMIDI1Protocol::UMPStreamParse(unsigned int)" 
(?UMPStreamParse@umpToMIDI1Protocol@@QEAAXI@Z)	Midi2.UmpProtocolDownscalerTransform)
```

To work around for the moment, I just stubbed out a body based on the other implementations. No idea if this works or matches your implementation.

```cpp
// TEMP due to missing libmidi2 function impl
void umpToMIDI1Protocol::increaseWrite()
{
    bufferLength++;
    writeIndex++;
    if (writeIndex == UMPTOPROTO1_BUFFER) {
        writeIndex = 0;
    }
}
```

**Comment by starfishmod** [comment]
Fixed in v0.10. Have sent new release to vcpkg as well
Have also created test scripts to stop the issues from occuring in the first place :/
